services:
  playground-frontend:
    networks:
      - celfocus-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    environment:
      - NEXT_PUBLIC_API_BASE_URL= http://host.docker.internal:8082/api
